version: "3"
services:
  postgres:
    image: "postgres:11.1-alpine"
    volumes:
      - watchtower_db_data:/var/lib/postgresql/data
    env_file:
      - .env_dev
    expose:
      - "5432"
  redis:
    image: "redis:alpine"
    env_file:
      - .env_dev
  backend:
    build: .
    command: [ "supervisord", "-c", "/code/supervisor/webserver.conf", "--nodaemon" ]
    ports:
      - "8000:8000"
    env_file:
      - .env_dev
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/code
      - /code/anyhedge/js/node_modules
volumes:
  watchtower_db_data:
    external: true