version: "3.7"
services:
  web:
    container_name: watchtower_web
    build: /root/watchtower
    image: watchtower_web
    command: [ "supervisord", "-c", "/code/supervisord.conf", "--nodaemon" ]
    env_file: /root/watchtower/compose/.env_prod
    volumes:
      - /var/www/images:/images
      - /code/anyhedge/js/node_modules
    ports:
      - 8000:8000
      - 9000:9000
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: on-failure
